In [3]:
import pandas as pd
m_cols=['movie_id','title','genre']
movies=pd.read_csv('./data/ml-10M100K/movies.dat',names=m_cols,sep='::',encoding='latin-1',engine='python')

In [4]:
movies

,movie_id,title,genre
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
10676,65088,Bedtime Stories (2008),Adventure|Children|Comedy
10677,65091,Manhattan Melodrama (1934),Crime|Drama|Romance
10678,65126,Choke (2008),Comedy|Drama
10679,65130,Revolutionary Road (2008),Drama|Romance
10680,65133,Blackadder Back & Forth (1999),Comedy

In [5]:
movies['genre']=movies.genre.apply(lambda x:x.split('|'))
movies.head()

,movie_id,title,genre
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II (1995),[Comedy]

In [6]:
t_cols=['user_id','movie_id','tag','timestamp']
user_tagged_movies=pd.read_csv('./data/ml-10M100K/tags.dat',names=t_cols,sep='::',engine='python')
user_tagged_movies['tag']=user_tagged_movies['tag'].str.lower()
user_tagged_movies.head()

   user_id  movie_id              tag   timestamp
0       15      4973       excellent!  1215184630
1       20      1747         politics  1188263867
2       20      1747           satire  1188263867
3       20      2424  chick flick 212  1188263835
4       20      2424            hanks  1188263835

In [15]:
print(len(user_tagged_movies.tag.unique()))
print(len(user_tagged_movies))
print(len(user_tagged_movies.movie_id.unique()))

15241
95580
7601

In [14]:
user_tagged_movies

       user_id  movie_id              tag   timestamp
0           15      4973       excellent!  1215184630
1           20      1747         politics  1188263867
2           20      1747           satire  1188263867
3           20      2424  chick flick 212  1188263835
4           20      2424            hanks  1188263835
...        ...       ...              ...         ...
95575    71556      1377           gothic  1188263571
95576    71556      2424      chick flick  1188263606
95577    71556      3033           comedy  1188263626
95578    71556      3081           gothic  1188263565
95579    71556      7438          western  1188263589

[95580 rows x 4 columns]

In [18]:
movie_tags=user_tagged_movies.groupby('movie_id').agg({'tag':list})

In [20]:
movies=movies.merge(movie_tags,on='movie_id',how='left')

In [ ]:
print(len(set(movies['tag'][0])))
movies.head()

r_cols=['user_id','movie_id','rating','timestamp']
ratings=pd.read_csv('./data/ml-10M100K/ratings.dat',names=r_cols,sep='::',engine='python')
ratings.head()

ratings['rating']#.unique()

63

   user_id  movie_id  rating  timestamp
0        1       122     5.0  838985046
1        1       185     5.0  838983525
2        1       231     5.0  838983392
3        1       292     5.0  838983421
4        1       316     5.0  838983392

In [ ]:
ratings['rating']#.unique()

array([5. , 3. , 2. , 4. , 4.5, 3.5, 1. , 1.5, 2.5, 0.5])